### ISSUE TITLE
Duplicate SMILES in finetuning set

### ISSUE THREAD

**Issue by linkerst** [bowang-lab/AGILE#12]
Hi, awesome work and thanks for sharing your code with us!

While working with the finetuning dataset in AGILE-main/data/finetuning_set_smiles_plus_features.csv I realized that although there are 1200 entries in the "smiles" column, there are only 1100 unique smiles. The smiles with the index 902-1001 are identical to the smiles at index 1002-1101. An example for a duplicate SMILE is this one : "CCCCCCCC\C=C/CCCCCCCCNC(=O)C(CCCCCOC(=O)\C=C\CCCCCCC)NCCCN(C)CCCN". 

Can you double check if you did a mistake in one of these sets? Having 100 incorrect entries might heavily influence the model.  

Thanks a lot!
Stephanie

**Comment by rexxxx1234** [comment]
Hi @linkerst, thanks for the comment!

We employ MarvinSketch for generating SMILES strings. Unfortunately, this software has a known limitation in accurately representing cis-trans isomerism. The following 2 tails in our finetuning dataset(see attached picture) are indeed cis-trans isomerism, which results in duplicate SMILES. This technical constraint is something we are currently mindful of and hope to address in future updates or with alternative solutions.

Your feedback is valuable in highlighting this aspect. Thanks again!

![isomerism](https://github.com/bowang-lab/AGILE/assets/19568928/aeed3751-da3c-46dd-b558-4a519905dd19)

**Comment by yuexu95** [comment]
The SMILES strings were enumerated using MARVIN (https://chemaxon.com/marvin), which has inherent limitations and cannot distinguish between cis and trans isomers. Addressing this issue would require manual annotation to clean the data, a highly time-intensive process. However, since the transfection potency of the cis and trans tails was found to be highly comparable, such efforts are unlikely to significantly enhance data quality.
