### ISSUE TITLE
mordred descriptor

### ISSUE THREAD

**Issue by lindafei01** [bowang-lab/AGILE#7]
Hi! Thank you for sharing AGILE code. 
I would like to know what does '/10' mean in 'desc_ABC/10' (a mordred descriptor used in AGILE). I've taken a look at the descriptor names of Mordred and learnt that 'ABC' is one of the descriptors.

**Comment by rexxxx1234** [comment]
Hi @lindafei01, thank you for your question.

The '/10' is the normalization factor for the descriptors, which means dividing the value of 'ABC' by 10. The reason for this is that we can't do the whole dataset normalization since it can have different scales from the training set and testing set. By applying such normalization using a constant value,  we can ensure the scale of our descriptors are consistent.
